### ISSUE TITLE
Types mismatch fails build

### ISSUE THREAD

**Issue by eyargilad** [InjectiveLabs/injective-ts#46]
![image](https://user-images.githubusercontent.com/93587179/176196867-1a0af8fa-5a8c-4a01-9fb3-fd7e61f3c49a.png)

**Comment by bangjelkoski** [comment]
Have you tried removing the `node_modules` and installing them again?

**Comment by eyargilad** [comment]
I did, it doesn't fix it. Adding ts-ignore to both functions does fix it.

**Comment by eyargilad** [comment]
Thank you :)

**Comment by bangjelkoski** [comment]
I can't reproduce this, is it still an issue? @eyargilad

**Comment by bangjelkoski** [comment]
Hey guys, I got a repro example and was able to reproduce the issue. Basically, the problem is that there is a field name "extension" within the `ContractInfo` interface, and having that name as a field shouldn't be the case because it overrides the default `extensions` field within the base Message interface from google's protobuf definition. If there is such a field name it should follow the convention from the Message interface. 

Wasmd types: https://github.com/CosmWasm/wasmd/blob/main/proto/cosmwasm/wasm/v1/types.proto#L94-L95
Types Generated: 
<img width="481" alt="image" src="https://user-images.githubusercontent.com/15016904/198128143-f226dc52-d732-410c-adb5-7246bc029bdb.png">
Base Message Definition: 
<img width="484" alt="image" src="https://user-images.githubusercontent.com/15016904/198128241-cb6ed20e-6929-4fbd-8717-e6149196c888.png">

So, to resolve this we have to skip checking the types within the imported libraries from the node_modules by using `"skipLibCheck": true` in tsconfig.json

**Comment by bangjelkoski** [comment]
I've just published a new version of the `sdk-ts` package that resolves the issue (basically does `@ts-ignore` on the lines that the compiler has issues with) without having the need to change the `tsconfig.json` file. 

```
Successfully published:
 - @injectivelabs/sdk-ts@1.0.189
 - @injectivelabs/wallet-ts@1.0.158
```
